config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: {
    sign_up: ''
  }
  resources :forms
  resources :trainings
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  root 'trainings#index' 
  get 'training/generate_forms', to: 'trainings#generate_forms'
  get '/trainingstype', to: "trainings#trainingtype"
  get '/trainingsindex', to: 'trainings#index'
  get '/custom_training', to: "trainings#custom"
  get '*path' => redirect('/')

end

app/models/form.rb
class Form < ActiveRecord::Base
    
end

app/models/trainings.rb
class Trainings < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  before_filter :authenticate_user!
  # before_filter do 
  #   redirect_to new_user_registration_path unless current_user
  # end
  before_action :set_form, only: [:show, :edit, :update, :destroy]
    
  # GET /forms
  # GET /forms.json
  def index
    @forms = Form.all
    @trainings = Trainings.all
  end

  # GET /forms/1
  # GET /forms/1.json
  def show
  end

  # GET /forms/new
  def new
    @type = params[:type]
    @sheet = params[:sheet]
    #default new view
  end

  # GET /forms/new_stc_forms_path
  def generate_forms
    @type = params[:type]
    @training = params[:training]
    if @type == "STC"
      @partial_type = "stc_partial"
    elsif @type == "NASW"
      @partial_type = "nasw_partial"
    elsif @type == "CE"
      @partial_type = "ce_partial"
    else
      @partial_type = "stc_partial"
    end
    # @type = "STC"
  end

  # GET /forms/1/edit
  def edit
  end

  # POST /forms
  # POST /forms.json
  def create
    @form = Form.create!(form_params)

 
    form_replace
    
    #flash[:notice] = "#{@form.type} was successfully created."
    #redirect_to forms_path
  end

  # PATCH/PUT /forms/1
  # PATCH/PUT /forms/1.json
  def update
    # respond_to do |format|
    #   if @form.update(form_params)
    #     format.html { redirect_to @form, notice: 'Form was successfully updated.' }
    #     format.json { render :show, status: :ok, location: @form }
    #   else
    #     format.html { render :edit }
    #     format.json { render json: @form.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /forms/1
  # DELETE /forms/1.json
  def destroy
    # @form.destroy
    # respond_to do |format|
    #   format.html { redirect_to forms_url, notice: 'Form was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
  end
  
  def form_replace
    #Using docx_replace gem
    #https://github.com/adamalbrecht/docx_replace
    
    doc = DocxReplace::Doc.new("#{Rails.root}/lib/form_templates/STC_Sign_In_Template_Public.docx", "#{Rails.root}/tmp")

    # Replace some variables. $var$ convention is used here, but not required.
    doc.replace("FIELD_REP", @form.stc_field_representative)
    doc.replace("CERT_NUMBER", @form.certification_number)
    doc.replace("START_DATE", @form.start_date)
    doc.replace("END_DATE", @form.end_date)
    doc.replace("LOCATION_TO_EDIT", @form.location)
    doc.replace("CERTIFIED_DATE", @form.certified_date)
    doc.replace("TITLE_COURSE", @form.course_title)
    doc.replace("TOTAL_PART", @form.total_participants)

    # Write the document back to a temporary file
    tmp_file = Tempfile.new('word_template', "#{Rails.root}/tmp")
    doc.commit(tmp_file.path)

    # Respond to the request by sending the temp file

    #flash[:notice] = "File Downloaded"
    
    #redirect_to new_form_path
    send_file tmp_file.path, filename: "STC_Sign_In_Sheet.docx", disposition: 'attachment'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_form
      @form = Form.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def form_params
      params.require(:form).permit(:stc_field_representative, :certification_number, :start_date, :end_date, :location, :certified_date, :course_title, :total_participants)
    end
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  before_filter :authenticate_user!
  # before_filter do 
  #   redirect_to new_user_registration_path unless current_user
  # end
  #before_action :set_Train, only: [:show, :edit, :update, :destroy]
  skip_before_filter :set_current_user

  # GET /trainings
  # GET /trainings.json
  def index
    @trainings = Trainings.all
  end
  
  def new
    # @type = params[:type]
    # @sheet = params[:sheet]
    # @id = params[:id]
    # @training = Trainings.find(@id)
    #default new view
  end
  
  def generate_forms
    @type = params[:type]
    @id = params[:id]
    @training = Trainings.find(@id)
    if @type == "STC"
      @partial_type = "stc_partial"
    elsif @type == "NASW"
      @partial_type = "nasw_partial"
    elsif @type == "CE"
      @partial_type = "ce_partial"
    else
      @partial_type = "other_partial"
    end
    # @type = "STC"
  end
  
  def create
    #@form = Form.create!(form_params)
    id = params[:id]
    @training = Trainings.find(id)
    @type = params[:type]
    @sheet = params[:commit]
 
    form_replace
    
    #flash[:notice] = "#{@form.type} was successfully created."
    #redirect_to forms_path
  end
  
  def form_replace
    #Using docx_replace gem
    #https://github.com/adamalbrecht/docx_replace
    
    if File.exist?("#{Rails.root}/lib/heroku_forms/"+@type+"_"+@sheet+".docx")
        doc = DocxReplace::Doc.new("#{Rails.root}/lib/heroku_forms/"+@type+"_"+@sheet+".docx", "#{Rails.root}/tmp")
      else
        doc = DocxReplace::Doc.new("#{Rails.root}/lib/form_templates/STC_Sign_In_Template_Public.docx", "#{Rails.root}/tmp")
      end
    
    # if @type != "STC" or @type != "CE" or @type != "NASW"
    #   if File.exist?("#{Rails.root}/lib/heroku_forms/"+@sheet+".docx")
    #     doc = DocxReplace::Doc.new("#{Rails.root}/lib/heroku_forms/"+@sheet+".docx", "#{Rails.root}/tmp")
    #   else
    #     doc = DocxReplace::Doc.new("#{Rails.root}/lib/form_templates/STC_Sign_In_Template_Public.docx", "#{Rails.root}/tmp")
    #   end
    # else
    #   if File.exist?("#{Rails.root}/lib/heroku_forms/"+@type+"_"+@sheet+".docx")
    #     doc = DocxReplace::Doc.new("#{Rails.root}/lib/heroku_forms/"+@type+"_"+@sheet+".docx", "#{Rails.root}/tmp")
    #   else
    #     doc = DocxReplace::Doc.new("#{Rails.root}/lib/form_templates/STC_Sign_In_Template_Public.docx", "#{Rails.root}/tmp")
    #   end
    # end


    # Replace some variables. $var$ convention is used here, but not required.
    doc.replace("FIELD_REP", @training.trainer)
    doc.replace("CERT_NUMBER", @training.certification_number)
    doc.replace("START_DATE", @training.course_start_date)
    doc.replace("END_DATE", @training.course_end_date)
    doc.replace("LOCATION_TO_EDIT", @training.location)
    #doc.replace("CERTIFIED_DATE", @training.certified_date)
    doc.replace("TITLE_COURSE", @training.training_title)
    #doc.replace("TOTAL_PART", @training.total_participants)

    # Write the document back to a temporary file
    tmp_file = Tempfile.new('word_template', "#{Rails.root}/tmp")
    doc.commit(tmp_file.path)

    # Respond to the request by sending the temp file

    #flash[:notice] = "File Downloaded"
    
    #redirect_to new_form_path

    send_file tmp_file.path, filename: @type+"_"+@sheet+"_Sheet.docx", disposition: 'attachment'
  end

  

  # GET /trainings/1
  # GET /trainings/1.json
  
  # def show
  # end
  
end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/views/Unused/forms/_ce_partial.html.haml
= link_to 'Generate Sign-in Sheet', new_form_path(:type => @type, :sheet => 'Sign_in', :training = @training)
%br
%br

app/views/Unused/forms/_form.html.haml
= form_for(@form) do |f|
  - if @form.errors.any?
    #error_explanation
      %h2
        = pluralize(@form.errors.count, "error")
        prohibited this form from being saved:
      %ul
        - @form.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :type
    %br/
    = f.text_field :type
  .actions
    = f.submit

app/views/Unused/forms/_nasw_partial.html.haml
= link_to 'Generate Sign-in Sheet', new_form_path(:type => @type, :sheet => 'Sign_in')
%br
%br

app/views/Unused/forms/_stc_partial.html.haml
= link_to 'Generate Sign-in Sheet', new_form_path(:type => @type, :sheet => 'Sign_in')
%br
%br
= link_to "Generate Course Evaluation", new_form_path(:type => @type, :sheet =>'Course Evaluation')
%br
%br
= link_to "Generate TCFT Completion Certificates", new_form_path(:type => @type, :sheet => 'TCFT Completion Certificate')
%br
%br
= link_to "Generate GCFT Completion Certificates", new_form_path(:type => @type, :sheet => 'GCFT Completion Certificate')
%br
%br

app/views/Unused/forms/edit.html.haml
%h1 Editing Form
= render 'form'
= link_to 'Show', @form
|
= link_to 'Back', forms_path

app/views/Unused/forms/generate_forms.html.haml
%h1 Generate Forms For: #{@type}
%title Generate Forms For: #{@type}


.content
  = render @partial_type
  
= link_to "Back", trainingtype_path

app/views/Unused/forms/index.html.haml
// %p#notice= notice
// %h1 Listing Forms
// %table
//   %thead
//     %tr
//       %th Type
//       %th{:colspan => "3"}
//   %tbody
//     - @forms.each do |form|
//       %tr
//         %td= form.type
//         %td= link_to 'Show', form
//         %td= link_to 'Edit', edit_form_path(form)
//         %td= link_to 'Destroy', form, method: :delete, data: { confirm: 'Are you sure?' }
// %br/
// = link_to 'New Form', new_form_path

%h1 Trainings Table

%table#trainings
    %thead
        %tr
            %th Training Title
            %th Training Type
            %th Trainer
            %th Location
            %th Certification Number
            %th Start Date
            %th End Date
    %tbody
        - @trainings.each do |training|
            %tr
                %td= training.training_title
                %td= training.training_type
                %td= training.trainer
                %td= training.location
                %td= training.certification_number
                %td= training.course_start_date
                %td= training.course_end_date
                %td= link_to "Generate", generate_forms_path(:type => "STC", :id => training)

app/views/Unused/forms/new.html.haml
%h1 Generate #{@type} #{@sheet}
%title Generate #{@type} #{@sheet}



= form_tag forms_path, :multipart=>true do

  = label :form, :stc_field_representative, 'Field Representative'
  = text_field :form, 'stc_field_representative'
  
  = label :form, :certification_number, 'Certification Number'
  = text_field :form, 'certification_number'
  
  = label :form, :start_date, 'Start Date'
  = text_field :form, 'start_date'
  
  = label :form, :end_date, 'End Date'
  = text_field :form, 'end_date'
  
  = label :form, :location, 'Location'
  = text_field :form, 'location'
  
  = label :form, :certified_date, 'Certified Date'
  = text_field :form, 'certified_date'
  
  = label :form, :course_title, 'Course Title'
  = text_field :form, 'course_title'
  
  = label :form, :total_participants, 'Total Participants'
  = text_field :form, 'total_participants'

  = file_field_tag :file

  = submit_tag 'Generate'

  
%br
%br
= link_to "Back", generate_forms_path(:type => @type)

app/views/Unused/forms/show.html.haml
%p#notice= notice
%p
  %strong Type:
  = @form.type
= link_to 'Edit', edit_form_path(@form)
|
= link_to 'Back', forms_path

app/views/Unused/forms/table.html.haml
%h1 Trainings Table

%table#trainings
    %thead
        %tr
            %th Training Title
            %th Training Type
            %th Trainer
            %th Location
            %th Certification Number
            %th Start Date
            %th End Date
    %tbody
        - @trainings.each do |training|
            %tr
                %td= training.training_title
                %td= training.training_type
                %td= training.location
                %td= training.certification_number
                %td= training.course_start_date
                %td= training.course_end_date
                %td= link_to "Generate", new_form_path, :method => :show
                =link_to 'Add new movie', new_movie_path

app/views/Unused/forms/trainingtype.html.haml
%h1 Training Types
%title Training Types

= link_to 'STC', generate_forms_path(:type => "STC")
%br
%br
= link_to 'NASW', generate_forms_path(:type => "NASW")
%br
%br
= link_to 'CE', generate_forms_path(:type => "CE")
%br

app/views/Unused/generate.html.haml
%h1 Generate STC Sign In Sheet

= form_tag forms_path do
  = label :form, :stc_field_representative, 'STC Field Representative'
  = text_field :movie, ':title'
//  
//   = label :movie, :title, 'Title'
//   = text_field :movie, 'title'
  
  = label :form, :certification_number, 'Certification Number'
  = text_field :form, ':certification_number'
  
  = label :form, :start_date, 'Start Date'
  = text_field :form, ':start_date'
  
  = label :form, :end_date, 'End Date'
  = text_field :form, ':end_date'
  
  = label :form, :location, 'Location'
  = text_field :form, ':location'
  
  = label :form, :certified_date, 'Certified Date'
  = text_field :form, ':certified_date'
  
  = label :form, :course_title, 'Course Title'
  = select :form, :course_title, ['The Council Facilitator Training', 'Girls Circle Facilitator Training']
  
  = label :form, :total_participants, 'Total Participants'
  = text_field :form, ':total_participants'

  = submit_tag 'Save Changes'

app/views/Unused/table.html.haml
%h1 Trainings Table

%table#trainings
    %thead
        %tr
            %th Training Title
            %th Training Type
            %th Trainer
            %th Location
            %th Certification Number
            %th Start Date
            %th End Date
    %tbody
        - @trainings.each do |training|
            %tr
                %td= training.training_title
                %td= training.training_type
                %td= training.location
                %td= training.certification_number
                %td= training.course_start_date
                %td= training.course_end_date
                %td= link_to "Generate", new_form_path, :method => :show
                =link_to 'Add new movie', new_movie_path

app/views/Unused/trainingtype.html.haml
%h1 Training Types
%title Training Types

= link_to 'STC', generate_forms_path(:type => "STC")
%br
%br
= link_to 'NASW', generate_forms_path(:type => "NASW")
%br
%br
= link_to 'CE', generate_forms_path(:type => "CE")
%br

app/views/forms/index.html.haml
%h1 <center>Trainings Table</center>

<head>
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://mottie.github.io/tablesorter/dist/js/jquery.tablesorter.min.js"></script>
</head>
<div class="input-group"> <span class="input-group-addon">Filter</span>
<input id="filter" type="text" class="form-control" placeholder="Type here...">
</div>


<table id="mytable" class="table table-striped table-hover table-condensed tablesorter">
<thead>
<tr bgcolor="#ff9933">
<th class="filterable-cell">Training Title</th>
<th>Training Type</th>
<th>Trainer</th>
<th>Location</th>
<th>Certification Number</th>
<th>Start Date</th>
<th>End Date</th>
<th>Forms</th>
</tr>
</thead>

<tbody class="searchable sortable">
- @trainings.each do |training|
  %tr
  %td= training.training_title
  %td= training.training_type
  %td= training.trainer
  %td= training.location
  %td= training.certification_number
  %td= training.course_start_date
  %td= training.course_end_date
  %td= link_to "Generate", new_form_path, :method => :show

</tbody>
</table>

<script>
$(document).ready(function () {
(function ($) {
$('#filter').keyup(function () {
var rex = new RegExp($(this).val(), 'i');
$('.searchable tr').hide();
$('.searchable tr').filter(function () {
return rex.test($(this).text());
}).show();
})
}(jQuery));
});
</script>

<script>
$(document).ready(function(){
$(function(){
$("#mytable").tablesorter();
});
});
</script>

app/views/forms/new.html.haml
%h1 Generate #{@type} #{@sheet}
%title Generate #{@type} #{@sheet}



= form_tag forms_path, :multipart=>true do

  = label :form, :stc_field_representative, 'Field Representative'
  = text_field :form, 'stc_field_representative'
  
  = label :form, :certification_number, 'Certification Number'
  = text_field :form, 'certification_number'
  
  = label :form, :start_date, 'Start Date'
  = text_field :form, 'start_date'
  
  = label :form, :end_date, 'End Date'
  = text_field :form, 'end_date'
  
  = label :form, :location, 'Location'
  = text_field :form, 'location'
  
  = label :form, :certified_date, 'Certified Date'
  = text_field :form, 'certified_date'
  
  = label :form, :course_title, 'Course Title'
  = text_field :form, 'course_title'
  
  = label :form, :total_participants, 'Total Participants'
  = text_field :form, 'total_participants'

  = file_field_tag :file

  = submit_tag 'Generate'

  
%br
%br
//= link_to "Back", generate_forms_path(:type => @type)

app/views/forms/newform.html.haml
%h1 Generate STC Forms
%title Generate STC Forms

= link_to 'Generate Sign-in Sheet', new_form_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title One Circle Admin
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %p.notice= notice
    %p.alert= alert
    = yield
    = render 'devise/shared/account_settings_link'
    = render 'devise/shared/login_link'
    

app/views/trainings/_ce_partial.html.haml
//= link_to 'Generate Sign-in Sheet', new_training_path(:type => @type, :sheet => 'Sign_in', :id => @id)
= form_tag trainings_path(:id => @id, :type => @type) do
    = submit_tag 'Generate Sign-in Sheet', value: "Sign_In"
    %br
    %br

app/views/trainings/_nasw_partial.html.haml
//= link_to 'Generate Sign-in Sheet', new_training_path(:type => @type, :sheet => 'Sign_in', :id => @id)
= form_tag trainings_path(:id => @id, :type => @type) do
    = submit_tag 'Generate Sign-in Sheet', value: "Sign_In"
    %br
    %br

app/views/trainings/_other_partial.html.haml
= form_tag trainings_path(:id => @id, :type => @type) do
    = submit_tag 'Generate Sign-in Sheet', value: "STC_Sign_In"
    %br
    %br
    = submit_tag('Generate Course Evaluation', value: "STC_Course_Evaluation")
    %br
    %br
    = submit_tag('Generate TCFT Completion Certificates', value: "STC_TCFT_Completion_Certificate")
    %br
    %br
    = submit_tag('Generate GCFT Completion Certificates', value: "STC_GCFT_Completion_Certificate")
    %br
    %br
    = submit_tag 'Generate Sign-in Sheet', value: "CE_Sign_In"
    %br
    %br
    = submit_tag 'Generate Sign-in Sheet', value: "NASW_Sign_In"
    %br
    %br

app/views/trainings/_stc_partial.html.haml
// = link_to 'Generate Sign-in Sheet', new_training_path(:type => @type, :sheet => 'Sign_in', :id => @id)
// %br
// %br
// = link_to "Generate Course Evaluation", new_training_path(:type => @type, :sheet =>'Course Evaluation', :id => @id)
// %br
// %br
// = link_to "Generate TCFT Completion Certificates", new_training_path(:type => @type, :sheet => 'TCFT Completion Certificate', :id => @id)
// %br
// %br
// = link_to "Generate GCFT Completion Certificates", new_training_path(:type => @type, :sheet => 'GCFT Completion Certificate', :id => @id)
// %br
// %br

= form_tag trainings_path(:id => @id, :type => @type) do
    = submit_tag 'Generate Sign-in Sheet', value: "Sign_In"
    %br
    %br
    = submit_tag('Generate Course Evaluation', value: "Course_Evaluation")
    %br
    %br
    = submit_tag('Generate TCFT Completion Certificates', value: "TCFT_Completion_Certificate")
    %br
    %br
    = submit_tag('Generate GCFT Completion Certificates', value: "GCFT_Completion_Certificate")
    %br
    %br

app/views/trainings/generate_forms.html.haml
%h1 Generate Forms For: #{@type}
%title Generate Forms For: #{@type}


.content
  = render @partial_type
  
= link_to "Back", trainingsindex_path

app/views/trainings/index.html.haml
%h1 <center>Trainings Table</center>

<head>
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://mottie.github.io/tablesorter/dist/js/jquery.tablesorter.min.js"></script>
</head>
<div class="input-group"> <span class="input-group-addon">Filter</span>
<input id="filter" type="text" class="form-control" placeholder="Type here...">
</div>

<table id="mytable" class="table table-striped table-hover table-condensed tablesorter">
<thead>
<tr bgcolor="#ff9933">
<th class="filterable-cell">Training Title</th>
<th>Training Type</th>
<th>Trainer</th>
<th>Location</th>
<th>Certification Number</th>
<th>Start Date</th>
<th>End Date</th>
<th>Forms</th>
</tr>
</thead>

<tbody class="searchable sortable">
- @trainings.each do |training|
  %tr
    %td= training.training_title
    %td= training.training_type
    %td= training.trainer
    %td= training.location
    %td= training.certification_number
    %td= training.course_start_date
    %td= training.course_end_date
    %td= link_to "Generate", training_generate_forms_path(:id => training, :type => training.training_type)
  //:method => :show

</tbody>
</table>

<script>
$(document).ready(function () {
(function ($) {
$('#filter').keyup(function () {
var rex = new RegExp($(this).val(), 'i');
$('.searchable tr').hide();
$('.searchable tr').filter(function () {
return rex.test($(this).text());
}).show();
})
}(jQuery));
});
</script>

<script>
$(document).ready(function(){
$(function(){
$("#mytable").tablesorter();
});
});
</script>

app/views/trainings/new.html.haml
%h1 Generate Custom
%title Generate Custom

= form_tag custom_training_path, :multipart=>true do

  = label :form, :stc_field_representative, 'Field Representative'
  = text_field :form, 'stc_field_representative'
  
  = label :form, :certification_number, 'Certification Number'
  = text_field :form, 'certification_number'
  
  = label :form, :start_date, 'Start Date'
  = text_field :form, 'start_date'
  
  = label :form, :end_date, 'End Date'
  = text_field :form, 'end_date'
  
  = label :form, :location, 'Location'
  = text_field :form, 'location'
  
  = label :form, :certified_date, 'Certified Date'
  = text_field :form, 'certified_date'
  
  = label :form, :course_title, 'Course Title'
  = text_field :form, 'course_title'
  
  = label :form, :total_participants, 'Total Participants'
  = text_field :form, 'total_participants'

  = file_field_tag :file

  = submit_tag 'Generate'

  
%br
%br
= link_to "Back", training_generate_forms_path(:type => @type, :id => @id)